// cantonese_full_db.js - 500句完整粤语数据库
// 10个关卡，每关50句，共500句

const CANTONESE_FULL_DB = {
  // ==================== 第1关：基础问候 (50句) ====================
  1: [
    { c: "你好", j: "nei5 hou2", m: "你好" },
    { c: "早晨", j: "zou2 san4", m: "早上好" },
    { c: "晚安", j: "maan5 on1", m: "晚安" },
    { c: "再见", j: "zoi3 gin3", m: "再见" },
    { c: "拜拜", j: "baai1 baai3", m: "拜拜" },
    { c: "你好吗", j: "nei5 hou2 maa3", m: "你好吗" },
    { c: "我很好", j: "ngo5 han2 hou2", m: "我很好" },
    { c: "最近点样", j: "zeoi3 gan6 dim2 joeng2", m: "最近怎么样" },
    { c: "好久不见", j: "hou2 noi6 bat1 gin3", m: "好久不见" },
    { c: "好耐冇见", j: "hou2 noi6 mou5 gin3", m: "好久不见" },
    { c: "你叫咩名", j: "nei5 giu3 me1 meng2", m: "你叫什么名字" },
    { c: "我系小明", j: "ngo5 hai6 siu2 ming4", m: "我是小明" },
    { c: "你几多岁", j: "nei5 gei2 do1 seoi3", m: "你多大年纪" },
    { c: "我二十岁", j: "ngo5 ji6 sap6 seoi3", m: "我二十岁" },
    { c: "你住边度", j: "nei5 zyu6 bin1 dou6", m: "你住哪里" },
    { c: "我住香港", j: "ngo5 zyu6 hoeng1 gong2", m: "我住香港" },
    { c: "你做边行", j: "nei5 zou6 bin1 hong4", m: "你做什么工作" },
    { c: "我系学生", j: "ngo5 hai6 hok6 saang1", m: "我是学生" },
    { c: "你中意咩", j: "nei5 zung1 ji3 me1", m: "你喜欢什么" },
    { c: "我好中意你", j: "ngo5 hou2 zung1 ji3 nei5", m: "我很喜欢你" },
    { c: "多谢你", j: "do1 ze6 nei5", m: "谢谢你" },
    { c: "辛苦晒", j: "san1 fu2 saai3", m: "辛苦了" },
    { c: "恭喜发财", j: "gung1 hei2 faat3 coi4", m: "恭喜发财" },
    { c: "新年快乐", j: "san1 nin4 faai3 lok6", m: "新年快乐" },
    { c: "生日快乐", j: "saang1 jat6 faai3 lok6", m: "生日快乐" },
    { c: "得闲饮茶", j: "dak1 haan4 jam2 caa4", m: "有空喝茶" },
    { c: "慢慢行", j: "maan6 maan6 haang4", m: "慢走" },
    { c: "下次见", j: "haa6 ci3 gin3", m: "下次见" },
    { c: "保持联络", j: "bou2 ci4 lyun4 lok3", m: "保持联系" },
    { c: "我好开心", j: "ngo5 hou2 hoi1 sam1", m: "我很开心" },
    { c: "我好兴奋", j: "ngo5 hou2 hing1 fan5", m: "我很兴奋" },
    { c: "我好感动", j: "ngo5 hou2 gam2 dung6", m: "我很感动" },
    { c: "我好幸福", j: "ngo5 hou2 hang6 fuk1", m: "我很幸福" },
    { c: "我好满足", j: "ngo5 hou2 mun5 zuk1", m: "我很满足" },
    { c: "一齐玩啦", j: "jat1 cai4 waan2 laa1", m: "一起玩吧" },
    { c: "得闲见", j: "dak1 haan4 gin3", m: "有空见" },
    { c: "听日见", j: "ting1 jat6 gin3", m: "明天见" },
    { c: "后日见", j: "hau6 jat6 gin3", m: "后天见" },
    { c: "下星期见", j: "haa6 sing1 kei4 gin3", m: "下周见" },
    { c: "保重身体", j: "bou2 zung6 san1 tai2", m: "保重身体" },
    { c: "注意安全", j: "zyu3 ji3 on1 cyun4", m: "注意安全" },
    { c: "一路顺风", j: "jat1 lou6 seon6 fung1", m: "一路顺风" },
    { c: "万事如意", j: "maan6 si6 jyu4 ji3", m: "万事如意" },
    { c: "心想事成", j: "sam1 soeng2 si6 sing4", m: "心想事成" },
    { c: "身体健康", j: "san1 tai2 gin6 hong1", m: "身体健康" },
    { c: "工作顺利", j: "gung1 zok3 seon6 lei6", m: "工作顺利" },
    { c: "学业进步", j: "hok6 jip6 zeon3 bou6", m: "学业进步" },
    { c: "青春常驻", j: "cing1 ceon1 soeng4 zyu3", m: "青春常驻" },
    { c: "笑口常开", j: "siu3 hau2 soeng4 hoi1", m: "笑口常开" },
    { c: "好运连连", j: "hou2 wan6 lin4 lin4", m: "好运连连" }
  ],

  // ==================== 第2关：礼貌用语 (50句) ====================
  2: [
    { c: "多谢", j: "do1 ze6", m: "谢谢" },
    { c: "唔该", j: "m4 goi1", m: "劳驾" },
    { c: "对唔住", j: "deoi3 m4 zyu6", m: "对不起" },
    { c: "唔好意思", j: "m4 hou2 ji3 si1", m: "不好意思" },
    { c: "冇问题", j: "mou5 man6 tai4", m: "没问题" },
    { c: "请", j: "ceng2", m: "请" },
    { c: "麻烦晒", j: "maa4 faan4 saai3", m: "麻烦你了" },
    { c: "唔紧要", j: "m4 gan2 jiu3", m: "不要紧" },
    { c: "得闲", j: "dak1 haan4", m: "有空" },
    { c: "是但", j: "si6 daan6", m: "随便" },
    { c: "随便", j: "ceoi4 bin6", m: "随便" },
    { c: "你话事", j: "nei5 waa6 si6", m: "你说了算" },
    { c: "我话事", j: "ngo5 waa6 si6", m: "我说了算" },
    { c: "大家话事", j: "daai6 gaa1 waa6 si6", m: "大家一起决定" },
    { c: "冇所谓", j: "mou5 so2 wai6", m: "无所谓" },
    { c: "求其啦", j: "kau4 kei4 laa1", m: "随便啦" },
    { c: "你决定", j: "nei5 kyut3 ding6", m: "你决定" },
    { c: "我赞成", j: "ngo5 zaan3 sing4", m: "我赞成" },
    { c: "我反对", j: "ngo5 faan2 deoi3", m: "我反对" },
    { c: "我同意", j: "ngo5 tung4 ji3", m: "我同意" },
    { c: "我拒绝", j: "ngo5 keoi5 zyu6", m: "我拒绝" },
    { c: "可以", j: "ho2 ji5", m: "可以" },
    { c: "唔可以", j: "m4 ho2 ji5", m: "不可以" },
    { c: "知道", j: "zi1 dou3", m: "知道" },
    { c: "唔知道", j: "m4 zi1 dou3", m: "不知道" },
    { c: "明白", j: "ming4 baak6", m: "明白" },
    { c: "唔明白", j: "m4 ming4 baak6", m: "不明白" },
    { c: "记得", j: "gei3 dak1", m: "记得" },
    { c: "唔记得", j: "m4 gei3 dak1", m: "不记得" },
    { c: "识得", j: "sik1 dak1", m: "认识" },
    { c: "唔识得", j: "m4 sik1 dak1", m: "不认识" },
    { c: "识做", j: "sik1 zou6", m: "会做" },
    { c: "唔识做", j: "m4 sik1 zou6", m: "不会做" },
    { c: "识听", j: "sik1 ting1", m: "听得懂" },
    { c: "唔识听", j: "m4 sik1 ting1", m: "听不懂" },
    { c: "识讲", j: "sik1 gong2", m: "会说" },
    { c: "唔识讲", j: "m4 sik1 gong2", m: "不会说" },
    { c: "你讲得啱", j: "nei5 gong2 dak1 aam1", m: "你说得对" },
    { c: "我同意你", j: "ngo5 tung4 ji3 nei5", m: "我同意你" },
    { c: "你讲得冇错", j: "nei5 gong2 dak1 mou5 co3", m: "你说得没错" },
    { c: "你讲得啱晒", j: "nei5 gong2 dak1 aam1 saai3", m: "你说得全对" },
    { c: "有道理", j: "jau5 dou6 lei5", m: "有道理" },
    { c: "原来如此", j: "jyun4 loi4 jyu4 ci2", m: "原来如此" },
    { c: "怪唔之得", j: "gwaai3 m4 zi1 dak1", m: "怪不得" },
    { c: "原来系咁", j: "jyun4 loi4 hai6 gam2", m: "原来是这样" },
    { c: "我都系咁话", j: "ngo5 dou1 hai6 gam2 waa6", m: "我也这么认为" },
    { c: "英雄所见略同", j: "jing1 hung4 so2 gin3 loek6 tung4", m: "英雄所见略同" },
    { c: "冇错", j: "mou5 co3", m: "没错" },
    { c: "绝对系", j: "zyut6 deoi3 hai6", m: "绝对是" },
    { c: "肯定系", j: "hang2 ding6 hai6", m: "肯定是" }
  ],

  // ==================== 第3关：饮食点餐 (50句) ====================
  3: [
    { c: "食咗饭未", j: "sik6 zo2 faan6 mei6", m: "吃饭了吗" },
    { c: "我想点菜", j: "ngo5 soeng2 dim2 coi3", m: "我想点菜" },
    { c: "唔该俾张菜单", j: "m4 goi1 bei2 zoeng1 caai3 daan1", m: "请给我菜单" },
    { c: "有冇推荐", j: "jau5 mou5 teoi1 zin3", m: "有推荐吗" },
    { c: "我要一杯奶茶", j: "ngo5 jiu3 jat1 bui1 naai5 caa4", m: "我要一杯奶茶" },
    { c: "冻饮", j: "dung3 jam2", m: "冷饮" },
    { c: "热饮", j: "jit6 jam2", m: "热饮" },
    { c: "打包", j: "daa2 baau1", m: "打包" },
    { c: "堂食", j: "tong4 sik6", m: "堂食" },
    { c: "几多钱", j: "gei2 do1 cin2", m: "多少钱" },
    { c: "埋单", j: "maai4 daan1", m: "买单" },
    { c: "好食", j: "hou2 sik6", m: "好吃" },
    { c: "好好味", j: "hou2 hou2 mei6", m: "很好吃" },
    { c: "太咸", j: "taai3 haam4", m: "太咸" },
    { c: "太甜", j: "taai3 tim4", m: "太甜" },
    { c: "太辣", j: "taai3 laat6", m: "太辣" },
    { c: "太酸", j: "taai3 syun1", m: "太酸" },
    { c: "太苦", j: "taai3 fu2", m: "太苦" },
    { c: "淡咗啲", j: "taam5 zo2 di1", m: "淡了一点" },
    { c: "咸咗啲", j: "haam4 zo2 di1", m: "咸了一点" },
    { c: "甜咗啲", j: "tim4 zo2 di1", m: "甜了一点" },
    { c: "辣咗啲", j: "laat6 zo2 di1", m: "辣了一点" },
    { c: "我想要碗云吞面", j: "ngo5 soeng2 jiu3 wun2 wan4 tan1 min6", m: "我想要碗云吞面" },
    { c: "我想要碗牛腩面", j: "ngo5 soeng2 jiu3 wun2 ngau4 naam5 min6", m: "我想要碗牛腩面" },
    { c: "我想要碗叉烧饭", j: "ngo5 soeng2 jiu3 wun2 caa1 siu1 faan6", m: "我想要碗叉烧饭" },
    { c: "我想要碟炒牛河", j: "ngo5 soeng2 jiu3 dip6 caau2 ngau4 ho4", m: "我想要碟炒牛河" },
    { c: "我想要笼虾饺", j: "ngo5 soeng2 jiu3 lung4 haa1 gaau2", m: "我想要笼虾饺" },
    { c: "我想要笼烧卖", j: "ngo5 soeng2 jiu3 lung4 siu1 maai6", m: "我想要笼烧卖" },
    { c: "我想要碗白饭", j: "ngo5 soeng2 jiu3 wun2 baak6 faan6", m: "我想要碗白饭" },
    { c: "加底", j: "gaa1 dai2", m: "加量" },
    { c: "少饭", j: "siu2 faan6", m: "少饭" },
    { c: "多葱", j: "do1 cung1", m: "多葱" },
    { c: "少葱", j: "siu2 cung1", m: "少葱" },
    { c: "走葱", j: "zau2 cung1", m: "不要葱" },
    { c: "走青", j: "zau2 ceng1", m: "不要香菜" },
    { c: "多汁", j: "do1 zap1", m: "多汁" },
    { c: "少油", j: "siu2 jau4", m: "少油" },
    { c: "唔该加水", j: "m4 goi1 gaa1 seoi2", m: "请加水" },
    { c: "可以上菜未", j: "ho2 ji5 soeng5 coi3 mei6", m: "可以上菜了吗" },
    { c: "催一催单", j: "ceoi1 jat1 ceoi1 daan1", m: "催一下单" },
    { c: "有冇WiFi", j: "jau5 mou5 WiFi", m: "有WiFi吗" },
    { c: "密码系咩", j: "mat6 maa5 hai6 me1", m: "密码是什么" },
    { c: "可以支付宝吗", j: "ho2 ji5 zi1 fuu3 bou2 maa3", m: "可以用支付宝吗" },
    { c: "可以微信支付吗", j: "ho2 ji5 mei4 seon3 zi1 fuu3 maa3", m: "可以用微信支付吗" },
    { c: "收现金", j: "sau1 jin6 gam1", m: "收现金" },
    { c: "有冇发票", j: "jau5 mou5 faat3 piu3", m: "有发票吗" },
    { c: "可唔可以打包", j: "ho2 m4 ho2 ji5 daa2 baau1", m: "可以打包吗" },
    { c: "唔该帮我打包", j: "m4 goi1 bong1 ngo5 daa2 baau1", m: "请帮我打包" }
  ],

  // ==================== 第4关：购物问价 (50句) ====================
  4: [
    { c: "几多钱", j: "gei2 do1 cin2", m: "多少钱" },
    { c: "太贵啦", j: "taai3 gwai3 laa1", m: "太贵了" },
    { c: "平啲啦", j: "peng4 di1 laa1", m: "便宜点吧" },
    { c: "我要呢个", j: "ngo5 jiu3 nei1 go3", m: "我要这个" },
    { c: "俾我睇下", j: "bei2 ngo5 tai2 haa5", m: "给我看一下" },
    { c: "有冇大码", j: "jau5 mou5 daai6 maa5", m: "有大码吗" },
    { c: "有冇细码", j: "jau5 mou5 sai3 maa5", m: "有小码吗" },
    { c: "可以试下吗", j: "ho2 ji5 si3 haa5 maa3", m: "可以试穿吗" },
    { c: "试衣室喺边度", j: "si3 ji1 sat1 hai2 bin1 dou6", m: "试衣间在哪里" },
    { c: "唔要", j: "m4 jiu3", m: "不要" },
    { c: "就要呢个", j: "zau6 jiu3 nei1 go3", m: "就要这个" },
    { c: "有冇折扣", j: "jau5 mou5 zit3 kau3", m: "有折扣吗" },
    { c: "打几多折", j: "daa2 gei2 do1 zit3", m: "打几折" },
    { c: "有冇优惠", j: "jau5 mou5 jau1 wai6", m: "有优惠吗" },
    { c: "呢个款式好靓", j: "nei1 go3 fun2 sik1 hou2 leng3", m: "这个款式很漂亮" },
    { c: "呢个颜色好衬我", j: "nei1 go3 ngaan4 sik1 hou2 can3 ngo5", m: "这个颜色很适合我" },
    { c: "有冇其他颜色", j: "jau5 mou5 kei4 taa1 ngaan4 sik1", m: "有其他颜色吗" },
    { c: "有冇其他款式", j: "jau5 mou5 kei4 taa1 fun2 sik1", m: "有其他款式吗" },
    { c: "呢个太细", j: "nei1 go3 taai3 sai3", m: "这个太小" },
    { c: "呢个太大", j: "nei1 go3 taai3 daai6", m: "这个太大" },
    { c: "呢个啱啱好", j: "nei1 go3 aam1 aam1 hou2", m: "这个刚刚好" },
    { c: "可以换货吗", j: "ho2 ji5 wun6 fo3 maa3", m: "可以换货吗" },
    { c: "可以退货吗", j: "ho2 ji5 teoi3 fo3 maa3", m: "可以退货吗" },
    { c: "有冇保养", j: "jau5 mou5 bou2 joeng5", m: "有保修吗" },
    { c: "买二送一", j: "maai5 ji6 sung3 jat1", m: "买二送一" },
    { c: "买三送一", j: "maai5 saam1 sung3 jat1", m: "买三送一" },
    { c: "买满五百蚊有礼物", j: "maai5 mun5 ng5 baak3 man1 jau5 lai5 mat6", m: "满五百元有礼物" },
    { c: "呢个系咩材料", j: "nei1 go3 hai6 me1 coi4 liu2", m: "这是什么材料" },
    { c: "呢个系咪真皮", j: "nei1 go3 hai6 mai6 zan1 pei4", m: "这是真皮吗" },
    { c: "呢个系咪纯棉", j: "nei1 go3 hai6 mai6 seon4 min4", m: "这是纯棉吗" },
    { c: "可以平啲吗", j: "ho2 ji5 peng4 di1 maa3", m: "可以便宜点吗" },
    { c: "最平几多", j: "zeoi3 peng4 gei2 do1", m: "最便宜多少" },
    { c: "最贵几多", j: "zeoi3 gwai3 gei2 do1", m: "最贵多少" },
    { c: "有冇学生优惠", j: "jau5 mou5 hok6 saang1 jau1 wai6", m: "有学生优惠吗" },
    { c: "有冇会员优惠", j: "jau5 mou5 wui6 jyun4 jau1 wai6", m: "有会员优惠吗" },
    { c: "点样成为会员", j: "dim2 joeng2 sing4 wai4 wui6 jyun4", m: "怎样成为会员" },
    { c: "可以用信用卡吗", j: "ho2 ji5 jung6 seon3 jung6 kaa1 maa3", m: "可以用信用卡吗" },
    { c: "可以分期吗", j: "ho2 ji5 fan1 kei4 maa3", m: "可以分期吗" },
    { c: "收唔收支付宝", j: "sau1 m4 sau1 zi1 fuu3 bou2", m: "收不收支付宝" },
    { c: "收唔收微信支付", j: "sau1 m4 sau1 mei4 seon3 zi1 fuu3", m: "收不收微信支付" },
    { c: "可以开单吗", j: "ho2 ji5 hoi1 daan1 maa3", m: "可以开单吗" },
    { c: "可以俾张收据我吗", j: "ho2 ji5 bei2 zoeng1 sau1 geoi3 ngo5 maa3", m: "可以给我收据吗" },
    { c: "我想退货", j: "ngo5 soeng2 teoi3 fo3", m: "我想退货" },
    { c: "我想换货", j: "ngo5 soeng2 wun6 fo3", m: "我想换货" },
    { c: "我想退款", j: "ngo5 soeng2 teoi3 faan2", m: "我想退款" },
    { c: "投诉电话系几多", j: "tau4 sou3 din6 waa2 hai6 gei2 do1", m: "投诉电话是多少" },
    { c: "我要见经理", j: "ngo5 jiu3 gin3 ging1 lei5", m: "我要见经理" },
    { c: "服务态度好差", j: "fuk6 mou6 taai3 dou6 hou2 caa1", m: "服务态度很差" },
    { c: "我会俾差评", j: "ngo5 wui5 bei2 caa1 ping4", m: "我会给差评" },
    { c: "下次唔会再嚟", j: "haa6 ci3 m4 wui5 zoi3 lei4", m: "下次不会再来了" }
  ],

  // ==================== 第5关：交通出行 (50句) ====================
  5: [
    { c: "巴士站喺边度", j: "baa1 si6 zaam6 hai2 bin1 dou6", m: "巴士站在哪里" },
    { c: "地铁站喺边度", j: "dei6 tit3 zaam6 hai2 bin1 dou6", m: "地铁站在哪里" },
    { c: "的士站喺边度", j: "dik1 si6 zaam6 hai2 bin1 dou6", m: "出租车站在哪里" },
    { c: "搭地铁去中环", j: "daap3 dei6 tit3 heoi3 zung1 waan4", m: "坐地铁去中环" },
    { c: "搭巴士去尖沙咀", j: "daap3 baa1 si6 heoi3 zim1 saa1 zeoi2", m: "坐巴士去尖沙咀" },
    { c: "搭的士去机场", j: "daap3 dik1 si6 heoi3 gei1 coeng4", m: "坐出租车去机场" },
    { c: "呢度落车", j: "nei1 dou6 lok6 ce1", m: "这里下车" },
    { c: "下一个站落车", j: "haa6 jat1 go3 zaam6 lok6 ce1", m: "下一站下车" },
    { c: "转巴士", j: "zyun3 baa1 si6", m: "转巴士" },
    { c: "转地铁", j: "zyun3 dei6 tit3", m: "转地铁" },
    { c: "搭的士", j: "daap3 dik1 si6", m: "坐出租车" },
    { c: "行路", j: "haang4 lou6", m: "走路" },
    { c: "踩单车", j: "caai2 daan1 ce1", m: "骑自行车" },
    { c: "搭船", j: "daap3 syun4", m: "坐船" },
    { c: "搭飞机", j: "daap3 fei1 gei1", m: "坐飞机" },
    { c: "八达通", j: "baat3 daat6 tung1", m: "八达通卡" },
    { c: "扫码", j: "soeng1 maa5", m: "扫码" },
    { c: "拍卡", j: "paak3 kaa1", m: "刷卡" },
    { c: "入钱", j: "jap6 cin2", m: "投币" },
    { c: "买飞", j: "maai5 fei1", m: "买票" },
    { c: "单程票", j: "daan1 cing4 piu3", m: "单程票" },
    { c: "来回票", j: "loi4 wui4 piu3", m: "往返票" },
    { c: "月票", j: "jyut6 piu3", m: "月票" },
    { c: "学生票", j: "hok6 saang1 piu3", m: "学生票" },
    { c: "长者票", j: "zoeng2 ze2 piu3", m: "老年票" },
    { c: "头等舱", j: "tau4 dang2 cong1", m: "头等舱" },
    { c: "经济舱", j: "ging1 zai3 cong1", m: "经济舱" },
    { c: "商务舱", j: "soeng1 mou6 cong1", m: "商务舱" },
    { c: "靠窗位", j: "kaau3 coeng1 wai2", m: "靠窗位置" },
    { c: "走廊位", j: "zau2 long4 wai2", m: "过道位置" },
    { c: "几多号巴士", j: "gei2 do1 hou6 baa1 si6", m: "几路巴士" },
    { c: "几多号地铁", j: "gei2 do1 hou6 dei6 tit3", m: "几号线地铁" },
    { c: "头班车几点", j: "tau4 baan1 ce1 gei2 dim2", m: "首班车几点" },
    { c: "尾班车几点", j: "mei5 baan1 ce1 gei2 dim2", m: "末班车几点" },
    { c: "几耐一班车", j: "gei2 noi6 jat1 baan1 ce1", m: "多久一班车" },
    { c: "会唔会迟到", j: "wui5 m4 wui5 ci4 dou3", m: "会不会迟到" },
    { c: "要几耐到", j: "jiu3 gei2 noi6 dou3", m: "要多久到" },
    { c: "赶时间", j: "gon2 si4 gaan3", m: "赶时间" },
    { c: "塞车", j: "sak1 ce1", m: "堵车" },
    { c: "交通意外", j: "gaau1 tung1 ji3 ngoi6", m: "交通事故" },
    { c: "改道", j: "goi2 dou6", m: "改道" },
    { c: "封路", j: "fung1 lou6", m: "封路" },
    { c: "修路", j: "sau1 lou6", m: "修路" },
    { c: "小心车辆", j: "siu2 sam1 ce1 loeng2", m: "小心车辆" },
    { c: "睇红绿灯", j: "tai2 hung4 luk6 dang1", m: "看红绿灯" },
    { c: "行人过路线", j: "haang4 jan4 gwo3 lou6 sin3", m: "人行横道" },
    { c: "天桥", j: "tin1 kiu4", m: "天桥" },
    { c: "隧道", j: "seoi6 dou6", m: "隧道" },
    { c: "电梯", j: "din6 tai1", m: "电梯" },
    { c: "扶手电梯", j: "fu4 sau2 din6 tai1", m: "自动扶梯" }
  ],

  // ==================== 第6关：问路求助 (50句) ====================
  6: [
    { c: "向左转", j: "heong3 zo2 zyun3", m: "向左转" },
    { c: "向右转", j: "heong3 jau6 zyun3", m: "向右转" },
    { c: "直行", j: "zik6 haang4", m: "直走" },
    { c: "喺边度", j: "hai2 bin1 dou6", m: "在哪里" },
    { c: "附近有冇", j: "fu6 gan6 jau5 mou5", m: "附近有没有" },
    { c: "点样去", j: "dim2 joeng2 heoi3", m: "怎么去" },
    { c: "过马路", j: "gwo3 maa5 lou6", m: "过马路" },
    { c: "上楼梯", j: "soeng5 lau4 tai1", m: "上楼梯" },
    { c: "落楼梯", j: "lok6 lau4 tai1", m: "下楼梯" },
    { c: "前面", j: "cin4 min6", m: "前面" },
    { c: "后面", j: "hau6 min6", m: "后面" },
    { c: "左边", j: "zo2 bin1", m: "左边" },
    { c: "右边", j: "jau6 bin1", m: "右边" },
    { c: "喺转角位", j: "hai2 zyun3 gok3 wai2", m: "在转角处" },
    { c: "喺对面", j: "hai2 deoi3 min6", m: "在对面" },
    { c: "喺隔篱", j: "hai2 gaak3 lei4", m: "在旁边" },
    { c: "好近", j: "hou2 gan6", m: "很近" },
    { c: "好远", j: "hou2 jyun5", m: "很远" },
    { c: "行路十分钟", j: "haang4 lou6 sap6 fan1 zung3", m: "走路十分钟" },
    { c: "搭车五分钟", j: "daap3 ce1 ng5 fan1 zung3", m: "坐车五分钟" },
    { c: "厕所喺边度", j: "ci3 so2 hai2 bin1 dou6", m: "厕所在哪里" },
    { c: "ATM喺边度", j: "ATM hai2 bin1 dou6", m: "ATM在哪里" },
    { c: "便利店喺边度", j: "bin6 lei6 dim3 hai2 bin1 dou6", m: "便利店在哪里" },
    { c: "药房喺边度", j: "joek6 fong2 hai2 bin1 dou6", m: "药房在哪里" },
    { c: "医院喺边度", j: "ji1 jyun2 hai2 bin1 dou6", m: "医院在哪里" },
    { c: "警局喺边度", j: "ging2 guk6 hai2 bin1 dou6", m: "警察局在哪里" },
    { c: "邮局喺边度", j: "jau4 guk6 hai2 bin1 dou6", m: "邮局在哪里" },
    { c: "银行喺边度", j: "ngan4 hong4 hai2 bin1 dou6", m: "银行在哪里" },
    { c: "超市喺边度", j: "ciu1 si5 hai2 bin1 dou6", m: "超市在哪里" },
    { c: "商场喺边度", j: "soeng1 coeng4 hai2 bin1 dou6", m: "商场在哪里" },
    { c: "餐厅喺边度", j: "caan1 teng1 hai2 bin1 dou6", m: "餐厅在哪里" },
    { c: "酒店喺边度", j: "zau2 dim3 hai2 bin1 dou6", m: "酒店在哪里" },
    { c: "景点喺边度", j: "ging2 dim2 hai2 bin1 dou6", m: "景点在哪里" },
    { c: "可唔可以帮我", j: "ho2 m4 ho2 ji5 bong1 ngo5", m: "可以帮我吗" },
    { c: "我荡失路", j: "ngo5 dong6 sat1 lou6", m: "我迷路了" },
    { c: "我唔识路", j: "ngo5 m4 sik1 lou6", m: "我不认识路" },
    { c: "你可以带我去吗", j: "nei5 ho2 ji5 daai3 ngo5 heoi3 maa3", m: "你可以带我去吗" },
    { c: "你可以教我点行吗", j: "nei5 ho2 ji5 gaau3 ngo5 dim2 haang4 maa3", m: "你可以教我怎么走吗" },
    { c: "麻烦你", j: "maa4 faan4 nei5", m: "麻烦你" },
    { c: "打扰一下", j: "daa2 jiu5 jat1 haa5", m: "打扰一下" },
    { c: "唔该借借", j: "m4 goi1 ze3 ze3", m: "请让一让" },
    { c: "小心", j: "siu2 sam1", m: "小心" },
    { c: "救命", j: "gau3 meng6", m: "救命" },
    { c: "帮帮手", j: "bong1 bong1 sau2", m: "帮帮忙" },
    { c: "有冇人", j: "jau5 mou5 jan4", m: "有人吗" },
    { c: "可唔可以讲慢啲", j: "ho2 m4 ho2 ji5 gong2 maan6 di1", m: "可以说慢一点吗" },
    { c: "可唔可以写低俾我", j: "ho2 m4 ho2 ji5 se2 dai1 bei2 ngo5", m: "可以写下来给我吗" },
    { c: "我听唔明", j: "ngo5 ting1 m4 ming4", m: "我听不懂" },
    { c: "我明啦", j: "ngo5 ming4 laa1", m: "我懂了" },
    { c: "多谢你帮忙", j: "do1 ze6 nei5 bong1 mong4", m: "谢谢你的帮助" }
  ],

  // ==================== 第7关：时间与数字 (50句) ====================
  7: [
    { c: "今日", j: "gam1 jat6", m: "今天" },
    { c: "听日", j: "ting1 jat6", m: "明天" },
    { c: "寻日", j: "cam4 jat6", m: "昨天" },
    { c: "几点钟", j: "gei2 dim2 zung1", m: "几点钟" },
    { c: "而家", j: "ji4 gaa1", m: "现在" },
    { c: "一阵间", j: "jat1 zan6 gaan1", m: "一会儿" },
    { c: "等阵", j: "dang2 zan6", m: "等一下" },
    { c: "好快", j: "hou2 faai3", m: "很快" },
    { c: "好耐", j: "hou2 noi6", m: "很久" },
    { c: "准时", j: "zeon2 si4", m: "准时" },
    { c: "迟到", j: "ci4 dou3", m: "迟到" },
    { c: "早到", j: "zou2 dou3", m: "早到" },
    { c: "一", j: "jat1", m: "一" },
    { c: "二", j: "ji6", m: "二" },
    { c: "三", j: "saam1", m: "三" },
    { c: "四", j: "sei3", m: "四" },
    { c: "五", j: "ng5", m: "五" },
    { c: "六", j: "luk6", m: "六" },
    { c: "七", j: "cat1", m: "七" },
    { c: "八", j: "baat3", m: "八" },
    { c: "九", j: "gau2", m: "九" },
    { c: "十", j: "sap6", m: "十" },
    { c: "二十", j: "ji6 sap6", m: "二十" },
    { c: "三十", j: "saam1 sap6", m: "三十" },
    { c: "四十", j: "sei3 sap6", m: "四十" },
    { c: "五十", j: "ng5 sap6", m: "五十" },
    { c: "一百", j: "jat1 baak3", m: "一百" },
    { c: "一千", j: "jat1 cin1", m: "一千" },
    { c: "一万", j: "jat1 maan6", m: "一万" },
    { c: "第一个", j: "dai6 jat1 go3", m: "第一个" },
    { c: "第二个", j: "dai6 ji6 go3", m: "第二个" },
    { c: "上午", j: "soeng6 ng5", m: "上午" },
    { c: "下午", j: "haa6 ng5", m: "下午" },
    { c: "夜晚", j: "je6 maan5", m: "晚上" },
    { c: "凌晨", j: "ling4 san4", m: "凌晨" },
    { c: "星期一", j: "sing1 kei4 jat1", m: "星期一" },
    { c: "星期二", j: "sing1 kei4 ji6", m: "星期二" },
    { c: "星期三", j: "sing1 kei4 saam1", m: "星期三" },
    { c: "星期四", j: "sing1 kei4 sei3", m: "星期四" },
    { c: "星期五", j: "sing1 kei4 ng5", m: "星期五" },
    { c: "星期六", j: "sing1 kei4 luk6", m: "星期六" },
    { c: "星期日", j: "sing1 kei4 jat6", m: "星期日" },
    { c: "一月", j: "jat1 jyut6", m: "一月" },
    { c: "二月", j: "ji6 jyut6", m: "二月" },
    { c: "三月", j: "saam1 jyut6", m: "三月" },
    { c: "春季", j: "ceon1 gwai3", m: "春季" },
    { c: "夏季", j: "haa6 gwai3", m: "夏季" },
    { c: "秋季", j: "cau1 gwai3", m: "秋季" },
    { c: "冬季", j: "dung1 gwai3", m: "冬季" },
    { c: "一年", j: "jat1 nin4", m: "一年" }
  ],

  // ==================== 第8关：紧急情况 (50句) ====================
  8: [
    { c: "救命", j: "gau3 meng6", m: "救命" },
    { c: "报警", j: "bou3 ging2", m: "报警" },
    { c: "叫救护车", j: "giu3 gau3 wu6 ce1", m: "叫救护车" },
    { c: "火烛", j: "fo2 zuk1", m: "着火" },
    { c: "有人受伤", j: "jau5 jan4 sau3 soeng1", m: "有人受伤" },
    { c: "快啲走", j: "faai3 di1 zau2", m: "快走" },
    { c: "小心危险", j: "siu2 sam1 ngai4 him2", m: "小心危险" },
    { c: "帮我叫白车", j: "bong1 ngo5 giu3 baak6 ce1", m: "帮我叫救护车" },
    { c: "我唔舒服", j: "ngo5 m4 syu1 fuk6", m: "我不舒服" },
    { c: "我发烧", j: "ngo5 faat3 siu1", m: "我发烧" },
    { c: "我头痛", j: "ngo5 tau4 tung3", m: "我头痛" },
    { c: "我肚痛", j: "ngo5 tou5 tung3", m: "我肚子痛" },
    { c: "我受伤", j: "ngo5 sau3 soeng1", m: "我受伤了" },
    { c: "我被偷嘢", j: "ngo5 bei6 tau1 je5", m: "我被偷东西了" },
    { c: "我唔见咗银包", j: "ngo5 m4 gin3 zo2 ngan4 baau1", m: "我钱包不见了" },
    { c: "我唔见咗电话", j: "ngo5 m4 gin3 zo2 din6 waa2", m: "我手机不见了" },
    { c: "我唔见咗护照", j: "ngo5 m4 gin3 zo2 wu6 ziu3", m: "我护照不见了" },
    { c: "帮我报警", j: "bong1 ngo5 bou3 ging2", m: "帮我报警" },
    { c: "警察", j: "ging2 caat3", m: "警察" },
    { c: "消防员", j: "siu1 fong4 jyun4", m: "消防员" },
    { c: "救护员", j: "gau3 wu6 jyun4", m: "救护员" },
    { c: "附近有冇医院", j: "fu6 gan6 jau5 mou5 ji1 jyun2", m: "附近有医院吗" },
    { c: "附近有冇警局", j: "fu6 gan6 jau5 mou5 ging2 guk6", m: "附近有警察局吗" },
    { c: "最近嘅医院喺边度", j: "zeoi3 gan6 ge3 ji1 jyun2 hai2 bin1 dou6", m: "最近的医院在哪里" },
    { c: "打999", j: "daa2 gau2 gau2 gau2", m: "打999" },
    { c: "大使馆电话", j: "daai6 si3 gun2 din6 waa2", m: "大使馆电话" },
    { c: "我需要翻译", j: "ngo5 seoi1 jiu3 faan1 jik6", m: "我需要翻译" },
    { c: "我唔识讲粤语", j: "ngo5 m4 sik1 gong2 jyut6 jyu5", m: "我不会说粤语" },
    { c: "你识讲普通话吗", j: "nei5 sik1 gong2 pou2 tung1 waa2 maa3", m: "你会说普通话吗" },
    { c: "你识讲英文吗", j: "nei5 sik1 gong2 jing1 man2 maa3", m: "你会说英语吗" },
    { c: "请帮我", j: "ceng2 bong1 ngo5", m: "请帮我" },
    { c: "我遇到麻烦", j: "ngo5 jyu6 dou3 maa4 faan4", m: "我遇到麻烦了" },
    { c: "我系游客", j: "ngo5 hai6 jau4 haak3", m: "我是游客" },
    { c: "我来自中国", j: "ngo5 loi4 zi6 zung1 gwok3", m: "我来自中国" },
    { c: "紧急联络人", j: "gan2 gap1 lyun4 lok3 jan4", m: "紧急联系人" },
    { c: "过敏", j: "gwo3 man5", m: "过敏" },
    { c: "哮喘", j: "haau1 chyun2", m: "哮喘" },
    { c: "心脏病", j: "sam1 zong1 beng6", m: "心脏病" },
    { c: "糖尿病", j: "tong4 niu6 beng6", m: "糖尿病" },
    { c: "高血压", j: "gou1 hyut3 ngaat1", m: "高血压" },
    { c: "我嚟唔切", j: "ngo5 lei4 m4 cit3", m: "我来不及了" },
    { c: "等埋我", j: "dang2 maai4 ngo5", m: "等等我" },
    { c: "唔好行咁快", j: "m4 hou2 haang4 gam3 faai3", m: "不要走那么快" },
    { c: "我追唔到", j: "ngo5 zeoi1 m4 dou3", m: "我追不上" },
    { c: "我跑唔郁", j: "ngo5 paau2 m4 juk1", m: "我跑不动" },
    { c: "我好攰", j: "ngo5 hou2 gui6", m: "我很累" },
    { c: "我唞下先", j: "ngo5 tau2 haa5 sin1", m: "我先休息一下" },
    { c: "俾杯水我", j: "bei2 bui1 seoi2 ngo5", m: "给我一杯水" },
    { c: "我需要休息", j: "ngo5 seoi1 jiu3 jau1 sik1", m: "我需要休息" },
    { c: "多谢你帮忙", j: "do1 ze6 nei5 bong1 mong4", m: "谢谢你的帮助" }
  ],

  // ==================== 第9关：校园生活 (50句) ====================
  9: [
    { c: "上课", j: "soeng5 fo3", m: "上课" },
    { c: "落堂", j: "lok6 tong4", m: "下课" },
    { c: "放学", j: "fong3 hok6", m: "放学" },
    { c: "考试", j: "haau2 si5", m: "考试" },
    { c: "测验", j: "cak1 jim6", m: "测验" },
    { c: "交功课", j: "gaau1 gung1 fo3", m: "交作业" },
    { c: "图书馆", j: "tou4 syu1 gun2", m: "图书馆" },
    { c: "实验室", j: "sat6 jim6 sat1", m: "实验室" },
    { c: "操场", j: "cou1 coeng4", m: "操场" },
    { c: "礼堂", j: "lai5 tong4", m: "礼堂" },
    { c: "老师", j: "lou5 si1", m: "老师" },
    { c: "同学", j: "tung4 hok6", m: "同学" },
    { c: "校长", j: "haau6 zoeng2", m: "校长" },
    { c: "班主任", j: "baan1 zyu2 jam6", m: "班主任" },
    { c: "数学", j: "sou3 hok6", m: "数学" },
    { c: "英文", j: "jing1 man2", m: "英语" },
    { c: "中文", j: "zung1 man2", m: "语文" },
    { c: "物理", j: "mat6 lei5", m: "物理" },
    { c: "化学", j: "faa3 hok6", m: "化学" },
    { c: "生物", j: "sang1 mat6", m: "生物" },
    { c: "历史", j: "lik6 si2", m: "历史" },
    { c: "地理", j: "dei6 lei5", m: "地理" },
    { c: "体育", j: "tai2 juk6", m: "体育" },
    { c: "音乐", j: "jam1 ngok6", m: "音乐" },
    { c: "美术", j: "mei5 seot6", m: "美术" },
    { c: "功课好多", j: "gung1 fo3 hou2 do1", m: "作业很多" },
    { c: "考试好难", j: "haau2 si5 hou2 naan4", m: "考试很难" },
    { c: "我合格", j: "ngo5 hap6 gaak3", m: "我及格了" },
    { c: "我唔合格", j: "ngo5 m4 hap6 gaak3", m: "我不及格" },
    { c: "我攞A", j: "ngo5 lo2 A", m: "我拿A" },
    { c: "我攞B", j: "ngo5 lo2 B", m: "我拿B" },
    { c: "我攞C", j: "ngo5 lo2 C", m: "我拿C" },
    { c: "我考第一", j: "ngo5 haau2 dai6 jat1", m: "我考第一名" },
    { c: "我考第二", j: "ngo5 haau2 dai6 ji6", m: "我考第二名" },
    { c: "我考第三", j: "ngo5 haau2 dai6 saam1", m: "我考第三名" },
    { c: "奖学金", j: "zoeng2 hok6 gam1", m: "奖学金" },
    { c: "毕业", j: "bat1 jip6", m: "毕业" },
    { c: "升学", j: "sing1 hok6", m: "升学" },
    { c: "留学", j: "lau4 hok6", m: "留学" },
    { c: "交换生", j: "gaau1 wun6 saang1", m: "交换生" },
    { c: "大学", j: "daai6 hok6", m: "大学" },
    { c: "中学", j: "zung1 hok6", m: "中学" },
    { c: "小学", j: "siu2 hok6", m: "小学" },
    { c: "幼儿园", j: "jau4 ji4 jyun2", m: "幼儿园" },
    { c: "请病假", j: "ceng2 beng6 gaa3", m: "请病假" },
    { c: "请事假", j: "ceng2 si6 gaa3", m: "请事假" },
    { c: "迟到", j: "ci4 dou3", m: "迟到" },
    { c: "早退", j: "zou2 teoi3", m: "早退" },
    { c: "旷课", j: "kwong3 fo3", m: "旷课" },
    { c: "留堂", j: "lau4 tong4", m: "留校" }
  ],

  // ==================== 第10关：情感日常 (50句) ====================
  10: [
    { c: "好开心", j: "hou2 hoi1 sam1", m: "很开心" },
    { c: "好伤心", j: "hou2 soeng1 sam1", m: "很伤心" },
    { c: "好兴奋", j: "hou2 hing1 fan5", m: "很兴奋" },
    { c: "好紧张", j: "hou2 gan2 zoeng1", m: "很紧张" },
    { c: "好攰", j: "hou2 gui6", m: "很累" },
    { c: "好眼瞓", j: "hou2 ngaan5 fan3", m: "很困" },
    { c: "好肚饿", j: "hou2 tou5 ngo6", m: "很饿" },
    { c: "好口渴", j: "hou2 hau2 hot3", m: "很渴" },
    { c: "好嬲", j: "hou2 nau1", m: "很生气" },
    { c: "好惊", j: "hou2 geng1", m: "很害怕" },
    { c: "好幸福", j: "hou2 hang6 fuk1", m: "很幸福" },
    { c: "好感动", j: "hou2 gam2 dung6", m: "很感动" },
    { c: "好满足", j: "hou2 mun5 zuk1", m: "很满足" },
    { c: "好失望", j: "hou2 sat1 mong6", m: "很失望" },
    { c: "好无聊", j: "hou2 mou4 liu4", m: "很无聊" },
    { c: "好寂寞", j: "hou2 zik6 mok6", m: "很寂寞" },
    { c: "好挂住你", j: "hou2 gwaa3 zyu6 nei5", m: "很想你" },
    { c: "我爱你", j: "ngo5 oi3 nei5", m: "我爱你" },
    { c: "我中意你", j: "ngo5 zung1 ji3 nei5", m: "我喜欢你" },
    { c: "你系我嘅唯一", j: "nei5 hai6 ngo5 ge3 wai4 jat1", m: "你是我的唯一" },
    { c: "你好靓", j: "nei5 hou2 leng3", m: "你很漂亮" },
    { c: "你好型", j: "nei5 hou2 jing4", m: "你很帅" },
    { c: "你好可爱", j: "nei5 hou2 ho2 oi3", m: "你很可爱" },
    { c: "你好聪明", j: "nei5 hou2 cung1 ming4", m: "你很聪明" },
    { c: "你好善良", j: "nei5 hou2 sin3 loeng4", m: "你很善良" },
    { c: "我以你为荣", j: "ngo5 ji5 nei5 wai4 wing4", m: "我以你为荣" },
    { c: "加油", j: "gaa1 jau2", m: "加油" },
    { c: "努力", j: "nou5 lik6", m: "努力" },
    { c: "坚持", j: "gin1 ci4", m: "坚持" },
    { c: "唔好放弃", j: "m4 hou2 fong3 hei3", m: "不要放弃" },
    { c: "你一定得", j: "nei5 jat1 ding6 dak1", m: "你一定可以的" },
    { c: "我支持你", j: "ngo5 zi1 ci4 nei5", m: "我支持你" },
    { c: "我信你", j: "ngo5 seon3 nei5", m: "我相信你" },
    { c: "你系最好嘅", j: "nei5 hai6 zeoi3 hou2 ge3", m: "你是最好的" },
    { c: "今日好特别", j: "gam1 jat6 hou2 dak6 bit6", m: "今天很特别" },
    { c: "今日好难忘", j: "gam1 jat6 hou2 naan4 mong4", m: "今天很难忘" },
    { c: "今日好重要", j: "gam1 jat6 hou2 zung6 jiu3", m: "今天很重要" },
    { c: "我记得今日", j: "ngo5 gei3 dak1 gam1 jat6", m: "我记得今天" },
    { c: "我唔会忘记", j: "ngo5 m4 wui5 mong4 gei3", m: "我不会忘记" },
    { c: "多谢你嘅爱", j: "do1 ze6 nei5 ge3 oi3", m: "谢谢你的爱" },
    { c: "多谢你嘅关心", j: "do1 ze6 nei5 ge3 gwaan1 sam1", m: "谢谢你的关心" },
    { c: "多谢你嘅支持", j: "do1 ze6 nei5 ge3 zi1 ci4", m: "谢谢你的支持" },
    { c: "有你真好", j: "jau5 nei5 zan1 hou2", m: "有你真好" },
    { c: "识到你真好", j: "sik1 dou3 nei5 zan1 hou2", m: "认识你真好" },
    { c: "同你一齐好开心", j: "tung4 nei5 jat1 cai4 hou2 hoi1 sam1", m: "和你在一起很开心" },
    { c: "希望再见到你", j: "hei1 mong6 zoi3 gin3 dou3 nei5", m: "希望能再见到你" },
    { c: "保重", j: "bou2 zung6", m: "保重" },
    { c: "珍重", j: "zan1 zung6", m: "珍重" },
    { c: "后会有期", j: "hau6 wui6 jau5 kei4", m: "后会有期" },
    { c: "友谊万岁", j: "jau5 ji4 maan6 seoi3", m: "友谊万岁" }
  ]
};

// 统计并输出
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CANTONESE_FULL_DB;
}

console.log('=' .repeat(50));
console.log('📚 粤语闯关王 - 完整数据库加载成功');
console.log('=' .repeat(50));
let total = 0;
for (let i = 1; i <= 10; i++) {
  const count = CANTONESE_FULL_DB[i].length;
  total += count;
  console.log(`   第${i}关: ${count}句`);
}
console.log(`   🎯 总计: ${total}句 (10关 × 50句 = 500句)`);
console.log('=' .repeat(50));